# This makepkg configuration is put into ~/.makepkg.conf to be used inside the
# container. It provides sane defaults for `makepkg`.

# Performance Tuning

NPROC="$(nproc)"
MAKEFLAGS="-j$(nproc)"


# Directories

BUILDDIR=/tmp/makepkg
#PKGDEST="$HOME/packages"
SRCDEST="$HOME/sources"
SRCPKGDEST="$HOME/srcpackages"
