# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 callmetango for SonicDE.org

name: Build All and Publish

on:
  workflow_dispatch:
    inputs:
      build-needed:
        description: Force the build of all packages
        type: boolean
        default: false
      branch:
        description: The branch to build
        type: choice
        options:
          - beta
          - master
        default: master

defaults:
  run:
    shell: sh

env:
  CARCH: x86_64

jobs:
  _setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup workspace
        uses: callmetango/setup-workspace@HEAD
        with:
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}

      - name: Draft new release
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: |
          . setup-build-env.sh
          draft-new-release.sh "$REPOSITORY" "$STAGING_TAG" "$BUILD_NEEDED"

  sonic-accounts-integration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keyring
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-sso
      - sonic-qt-accounts-library
    with:
      package: sonic-accounts-integration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-activities:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-settings
    with:
      package: sonic-activities
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-activities-stats:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-settings
    with:
      package: sonic-activities-stats
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-activity-manager-daemon:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-settings
      - sonic-frameworks-xml-gui
    with:
      package: sonic-activity-manager-daemon
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-audio-applet-pulse:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-keybind
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-status-notification
      - sonic-frameworks-svg
      - sonic-interface-libraries
      - sonic-pulseaudio-library
      - sonic-workspace
    with:
      package: sonic-audio-applet-pulse
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-bluetooth-runtime:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-bluetooth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-notifications
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
    with:
      package: sonic-bluetooth-runtime
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-breeze:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-qt-integration
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-silver-icons
    with:
      package: sonic-breeze
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-breeze-sddm:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-workspace
    with:
      package: sonic-breeze-sddm
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-browser-integration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-file-metadata
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-progress-ui
      - sonic-frameworks-purpose
      - sonic-frameworks-settings
      - sonic-frameworks-status-notification
      - sonic-workspace
    with:
      package: sonic-browser-integration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-crypto-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-crypto-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-daemon:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-settings
    with:
      package: sonic-daemon
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-decoration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-internationalization
    with:
      package: sonic-decoration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-desktop-interface:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-accounts-integration
      - sonic-activities
      - sonic-activities-stats
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-autocomplete
      - sonic-frameworks-bookmarks
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-data-views
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-file-search
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notification-settings
      - sonic-frameworks-notifications
      - sonic-frameworks-open-collab
      - sonic-frameworks-package
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-settings-utils
      - sonic-frameworks-spell-check
      - sonic-frameworks-svg
      - sonic-frameworks-text-codec
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-interface-libraries
      - sonic-launcher-menu-edit
      - sonic-pipewire
      - sonic-plasma5-support-library
      - sonic-polkit-agent
      - sonic-system-monitor-library
      - sonic-workspace
    with:
      package: sonic-desktop-interface
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-disks:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-notifications
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-system-info
    with:
      package: sonic-disks
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-dr-robotnik:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keyring
      - sonic-frameworks-notifications
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-status-notification
      - sonic-frameworks-syntax-highlighting
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-polkit
    with:
      package: sonic-dr-robotnik
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-drawing-tablet:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-interface-libraries
      - sonic-plasma5-support-library
    with:
      package: sonic-drawing-tablet
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-ecco:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-autocomplete
      - sonic-frameworks-bookmarks
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-file-metadata
      - sonic-frameworks-file-search
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-io-extras
      - sonic-frameworks-notifications
      - sonic-frameworks-progress-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-settings-utils
      - sonic-frameworks-text-codec
      - sonic-frameworks-text-widgets
      - sonic-frameworks-ui-components
      - sonic-frameworks-user-feedback
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
    with:
      package: sonic-ecco
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-exiv2-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-exiv2-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-file-search-ui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-quick-ui
      - sonic-frameworks-runner
      - sonic-frameworks-settings
      - sonic-frameworks-svg
      - sonic-interface-libraries
    with:
      package: sonic-file-search-ui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-firewall:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
    with:
      package: sonic-firewall
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-addons-downloader:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-feeds
      - sonic-frameworks-internationalization
      - sonic-frameworks-open-collab
      - sonic-frameworks-package
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-addons-downloader
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-app-info:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-app-info
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-archive:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-archive
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-auth:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-windowsystem
      - sonic-polkit
    with:
      package: sonic-frameworks-auth
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-autocomplete:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-settings
      - sonic-frameworks-text-codec
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-autocomplete
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-barcode:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-barcode
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-bluetooth:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-bluetooth
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-bookmarks:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-bookmarks
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-cmake-modules:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-frameworks-cmake-modules
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-color-scheme:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-color-scheme
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-core-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-core-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-crash-handler:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
    with:
      package: sonic-frameworks-crash-handler
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-data-models:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-data-models
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-data-views:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-data-views
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-dbus:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-dbus
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-device-integration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-device-integration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-doctools:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-internationalization
    with:
      package: sonic-frameworks-doctools
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-feeds:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-text-codec
    with:
      package: sonic-frameworks-feeds
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-file-metadata:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
      - sonic-frameworks-text-codec
    with:
      package: sonic-frameworks-file-metadata
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-file-search:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-file-metadata
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-file-search
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-gui-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-gui-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-holidays:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-holidays
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-icon-themes:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
      - sonic-silver-icons
    with:
      package: sonic-frameworks-icon-themes
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-idle-tracker:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-idle-tracker
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-image-formats:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-image-formats
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-internationalization:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-internationalization
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-io:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-archive
      - sonic-frameworks-autocomplete
      - sonic-frameworks-bookmarks
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-views
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-keyring
      - sonic-frameworks-progress-ui
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-frameworks-io
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-io-extras:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-activities-stats
      - sonic-exiv2-library
      - sonic-frameworks-app-info
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-notifications
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-syntax-highlighting
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-zeroconf
    with:
      package: sonic-frameworks-io-extras
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-io-fuse:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
    with:
      package: sonic-frameworks-io-fuse
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-keybind:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-keybind
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-keyring:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-notifications
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-frameworks-keyring
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-keyring-pam:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-keyring
    with:
      package: sonic-frameworks-keyring-pam
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-modemmanager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-modemmanager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-networkmanager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-networkmanager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-notification-settings:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-notification-settings
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-notifications:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-settings
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-notifications
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-open-collab:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-open-collab
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-package:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
    with:
      package: sonic-frameworks-package
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-progress-ui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-notifications
      - sonic-frameworks-widgets-addons
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-progress-ui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-pseudo-terminal:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
    with:
      package: sonic-frameworks-pseudo-terminal
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-purpose:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-accounts-integration
      - sonic-frameworks-app-info
      - sonic-frameworks-barcode
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-notifications
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-qt-accounts-library
    with:
      package: sonic-frameworks-purpose
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-qml-bridge:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-keybind
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-qml-bridge
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-qt-integration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-notifications
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-qt-integration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-charts:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-quick-ui
    with:
      package: sonic-frameworks-quick-charts
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-desktop-style:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-icon-themes
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-spell-check
    with:
      package: sonic-frameworks-quick-desktop-style
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-silver-style:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-quick-silver-style
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-ui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-quick-ui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-ui-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-spell-check
      - sonic-frameworks-svg
    with:
      package: sonic-frameworks-quick-ui-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-root-shell:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-pseudo-terminal
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-root-shell
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-runner:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
      - sonic-frameworks-windowsystem
    with:
      package: sonic-frameworks-runner
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-settings:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-settings
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-settings-ui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
      - sonic-frameworks-text-codec
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-settings-ui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-settings-utils:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-views
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-xml-gui
    with:
      package: sonic-frameworks-settings-utils
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-spell-check:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-spell-check
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-sso:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-frameworks-sso
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-status-notification:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-windowsystem
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-status-notification
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-svg:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
    with:
      package: sonic-frameworks-svg
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-syntax-highlighting:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-syntax-highlighting
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-text-codec:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-text-codec
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-text-editor:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-auth
      - sonic-frameworks-autocomplete
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-views
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-spell-check
      - sonic-frameworks-syntax-highlighting
      - sonic-frameworks-text-codec
      - sonic-frameworks-ui-components
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-xml-gui
    with:
      package: sonic-frameworks-text-editor
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-text-widgets:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-autocomplete
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
      - sonic-frameworks-spell-check
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-frameworks-text-widgets
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-ui-components:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-xml-gui
    with:
      package: sonic-frameworks-ui-components
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-unit-conversion:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-internationalization
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-unit-conversion
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-user-feedback:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-user-feedback
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-widgets-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-widgets-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-windowsystem:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-windowsystem
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-xml-gui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-views
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-keybind
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-widgets-addons
      - sonic-pyside-setup
    with:
      package: sonic-frameworks-xml-gui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-zeroconf:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-zeroconf
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-gtk-theme-bridge:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-gui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-windowsystem
    with:
      package: sonic-gtk-theme-bridge
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-interface-libraries:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-svg
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-interface-libraries
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-keybind-daemon:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-progress-ui
      - sonic-frameworks-settings
      - sonic-frameworks-windowsystem
    with:
      package: sonic-keybind-daemon
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-launcher-menu-edit:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-autocomplete
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-views
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-spell-check
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
    with:
      package: sonic-launcher-menu-edit
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-login-manager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-package
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-screen-library
      - sonic-workspace
    with:
      package: sonic-login-manager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-mobile-interface:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-audio-applet-pulse
      - sonic-file-search-ui
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-bluetooth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-modemmanager
      - sonic-frameworks-networkmanager
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-network-manager
      - sonic-pipewire
      - sonic-screen-library
      - sonic-win
      - sonic-workspace
    with:
      package: sonic-mobile-interface
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-network-manager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-autocomplete
      - sonic-frameworks-barcode
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-modemmanager
      - sonic-frameworks-networkmanager
      - sonic-frameworks-notifications
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-charts
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-workspace
    with:
      package: sonic-network-manager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-night-light:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-holidays
      - sonic-frameworks-internationalization
      - sonic-frameworks-settings
    with:
      package: sonic-night-light
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-oxygen:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-autocomplete
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-qt-integration
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-settings-utils
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-oxygen-icons
    with:
      package: sonic-oxygen
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-oxygen-icons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-oxygen-icons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-oxygen-sounds:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-oxygen-sounds
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-partition-manager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-polkit
    with:
      package: sonic-partition-manager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-pipewire:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-internationalization
    with:
      package: sonic-pipewire
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-plasma5-support-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-device-integration
      - sonic-frameworks-gui-addons
      - sonic-frameworks-holidays
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-networkmanager
      - sonic-frameworks-notifications
      - sonic-frameworks-progress-ui
      - sonic-frameworks-settings
      - sonic-frameworks-unit-conversion
      - sonic-system-monitor-library
    with:
      package: sonic-plasma5-support-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-polkit:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-polkit
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-polkit-agent:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-notifications
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-polkit
    with:
      package: sonic-polkit-agent
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-pulseaudio-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-pulseaudio-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-pyside-setup:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-pyside-setup
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-qt-accounts-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-qt-accounts-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-qt-theme-bridge:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-progress-ui
      - sonic-frameworks-quick-desktop-style
      - sonic-frameworks-quick-silver-style
      - sonic-frameworks-settings
      - sonic-frameworks-status-notification
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-qt-theme-bridge
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-quick-image-editor:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
    with:
      package: sonic-quick-image-editor
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-rdp-server:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-status-notification
      - sonic-pipewire
    with:
      package: sonic-rdp-server
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screen:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-image-formats
      - sonic-frameworks-internationalization
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-plasma5-support-library
      - sonic-screen-library
    with:
      package: sonic-screen
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screen-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-screen-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screenies:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-barcode
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-progress-ui
      - sonic-frameworks-purpose
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-status-notification
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-pipewire
      - sonic-quick-image-editor
    with:
      package: sonic-screenies
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screenlocker:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-doctools
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-interface-libraries
      - sonic-screen-library
    with:
      package: sonic-screenlocker
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-qt-integration
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-silver-icons
    with:
      package: sonic-silver
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver-gtk:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-silver
    with:
      package: sonic-silver-gtk
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver-icons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-silver-icons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver-sddm:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-workspace
    with:
      package: sonic-silver-sddm
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-ssh-password-prompt:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-widgets-addons
    with:
      package: sonic-ssh-password-prompt
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-info:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
    with:
      package: sonic-system-info
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-log:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-archive
      - sonic-frameworks-autocomplete
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-views
      - sonic-frameworks-doctools
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-text-widgets
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-xml-gui
    with:
      package: sonic-system-log
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-monitor:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-charts
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-windowsystem
      - sonic-system-monitor-library
      - sonic-system-stats
    with:
      package: sonic-system-monitor
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-monitor-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-device-integration
      - sonic-frameworks-internationalization
      - sonic-frameworks-package
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-charts
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
    with:
      package: sonic-system-monitor-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-stats:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-device-integration
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-networkmanager
      - sonic-system-monitor-library
    with:
      package: sonic-system-stats
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-terminal:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-bookmarks
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notification-settings
      - sonic-frameworks-notifications
      - sonic-frameworks-pseudo-terminal
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-text-widgets
      - sonic-frameworks-ui-components
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
    with:
      package: sonic-terminal
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-terminal-tools:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-autocomplete
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-root-shell
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-ui-components
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-terminal-tools
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-thunderbolt:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-internationalization
      - sonic-frameworks-notifications
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings-utils
    with:
      package: sonic-thunderbolt
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-tv-interface:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-file-search-ui
      - sonic-frameworks-app-info
      - sonic-frameworks-bluetooth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-screen-library
      - sonic-workspace
    with:
      package: sonic-tv-interface
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-vault:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-networkmanager
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-widgets-addons
      - sonic-interface-libraries
      - sonic-system-monitor-library
      - sonic-workspace
    with:
      package: sonic-vault
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-welcome-center:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-dbus
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-progress-ui
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-user-feedback
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-network-manager
      - sonic-plasma5-support-library
    with:
      package: sonic-welcome-center
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-win:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-decoration
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-internationalization
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-charts
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-svg
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-interface-libraries
      - sonic-keybind-daemon
      - sonic-night-light
      - sonic-screenlocker
      - sonic-silver
    with:
      package: sonic-win
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-workspace:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-activities-stats
      - sonic-activity-manager-daemon
      - sonic-daemon
      - sonic-exiv2-library
      - sonic-file-search-ui
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-archive
      - sonic-frameworks-auth
      - sonic-frameworks-autocomplete
      - sonic-frameworks-barcode
      - sonic-frameworks-bookmarks
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-file-search
      - sonic-frameworks-gui-addons
      - sonic-frameworks-holidays
      - sonic-frameworks-icon-themes
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-io-extras
      - sonic-frameworks-io-fuse
      - sonic-frameworks-keybind
      - sonic-frameworks-keyring
      - sonic-frameworks-networkmanager
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-charts
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-settings-utils
      - sonic-frameworks-status-notification
      - sonic-frameworks-svg
      - sonic-frameworks-text-editor
      - sonic-frameworks-text-widgets
      - sonic-frameworks-ui-components
      - sonic-frameworks-user-feedback
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-interface-libraries
      - sonic-night-light
      - sonic-pipewire
      - sonic-screenlocker
      - sonic-system-monitor-library
      - sonic-system-stats
      - sonic-terminal-tools
      - sonic-win
    with:
      package: sonic-workspace
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-workspace-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-data-models
      - sonic-frameworks-dbus
      - sonic-frameworks-gui-addons
      - sonic-frameworks-holidays
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-networkmanager
      - sonic-frameworks-notifications
      - sonic-frameworks-package
      - sonic-frameworks-progress-ui
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-spell-check
      - sonic-frameworks-svg
      - sonic-frameworks-unit-conversion
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-interface-libraries
      - sonic-win
      - sonic-workspace
    with:
      package: sonic-workspace-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-workspace-wallpapers:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-workspace-wallpapers
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-write-daemon:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-dbus
      - sonic-frameworks-doctools
      - sonic-frameworks-notifications
      - sonic-frameworks-pseudo-terminal
    with:
      package: sonic-write-daemon
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonicde-meta:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities-stats
      - sonic-activity-manager-daemon
      - sonic-audio-applet-pulse
      - sonic-bluetooth-runtime
      - sonic-browser-integration
      - sonic-decoration
      - sonic-desktop-interface
      - sonic-disks
      - sonic-dr-robotnik
      - sonic-ecco
      - sonic-file-search-ui
      - sonic-firewall
      - sonic-frameworks-keyring-pam
      - sonic-gtk-theme-bridge
      - sonic-keybind-daemon
      - sonic-launcher-menu-edit
      - sonic-login-manager
      - sonic-network-manager
      - sonic-night-light
      - sonic-oxygen
      - sonic-oxygen-sounds
      - sonic-pipewire
      - sonic-polkit-agent
      - sonic-qt-theme-bridge
      - sonic-rdp-server
      - sonic-screen
      - sonic-screenies
      - sonic-screenlocker
      - sonic-silver
      - sonic-silver-gtk
      - sonic-ssh-password-prompt
      - sonic-system-info
      - sonic-system-monitor
      - sonic-system-stats
      - sonic-terminal
      - sonic-terminal-tools
      - sonic-thunderbolt
      - sonic-vault
      - sonic-welcome-center
      - sonic-workspace-addons
      - sonic-write-daemon
      - xdg-desktop-portal-sonicde
    with:
      package: sonicde-meta
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  xdg-desktop-portal-sonicde:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-app-info
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-views
      - sonic-frameworks-icon-themes
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-io-fuse
      - sonic-frameworks-keybind
      - sonic-frameworks-notifications
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-settings
      - sonic-frameworks-settings-utils
      - sonic-frameworks-status-notification
      - sonic-frameworks-windowsystem
      - sonic-pipewire
      - sonic-workspace
    with:
      package: xdg-desktop-portal-sonicde
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  all-packages:
    runs-on: ubuntu-24.04
    needs:
      - sonic-accounts-integration
      - sonic-activities
      - sonic-activities-stats
      - sonic-activity-manager-daemon
      - sonic-audio-applet-pulse
      - sonic-bluetooth-runtime
      - sonic-breeze
      - sonic-breeze-sddm
      - sonic-browser-integration
      - sonic-crypto-library
      - sonic-daemon
      - sonic-decoration
      - sonic-desktop-interface
      - sonic-disks
      - sonic-dr-robotnik
      - sonic-drawing-tablet
      - sonic-ecco
      - sonic-exiv2-library
      - sonic-file-search-ui
      - sonic-firewall
      - sonic-frameworks-addons-downloader
      - sonic-frameworks-app-info
      - sonic-frameworks-archive
      - sonic-frameworks-auth
      - sonic-frameworks-autocomplete
      - sonic-frameworks-barcode
      - sonic-frameworks-bluetooth
      - sonic-frameworks-bookmarks
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-crash-handler
      - sonic-frameworks-data-models
      - sonic-frameworks-data-views
      - sonic-frameworks-dbus
      - sonic-frameworks-device-integration
      - sonic-frameworks-doctools
      - sonic-frameworks-feeds
      - sonic-frameworks-file-metadata
      - sonic-frameworks-file-search
      - sonic-frameworks-gui-addons
      - sonic-frameworks-holidays
      - sonic-frameworks-icon-themes
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-image-formats
      - sonic-frameworks-internationalization
      - sonic-frameworks-io
      - sonic-frameworks-io-extras
      - sonic-frameworks-io-fuse
      - sonic-frameworks-keybind
      - sonic-frameworks-keyring
      - sonic-frameworks-keyring-pam
      - sonic-frameworks-modemmanager
      - sonic-frameworks-networkmanager
      - sonic-frameworks-notification-settings
      - sonic-frameworks-notifications
      - sonic-frameworks-open-collab
      - sonic-frameworks-package
      - sonic-frameworks-progress-ui
      - sonic-frameworks-pseudo-terminal
      - sonic-frameworks-purpose
      - sonic-frameworks-qml-bridge
      - sonic-frameworks-qt-integration
      - sonic-frameworks-quick-charts
      - sonic-frameworks-quick-desktop-style
      - sonic-frameworks-quick-silver-style
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-root-shell
      - sonic-frameworks-runner
      - sonic-frameworks-settings
      - sonic-frameworks-settings-ui
      - sonic-frameworks-settings-utils
      - sonic-frameworks-spell-check
      - sonic-frameworks-sso
      - sonic-frameworks-status-notification
      - sonic-frameworks-svg
      - sonic-frameworks-syntax-highlighting
      - sonic-frameworks-text-codec
      - sonic-frameworks-text-editor
      - sonic-frameworks-text-widgets
      - sonic-frameworks-ui-components
      - sonic-frameworks-unit-conversion
      - sonic-frameworks-user-feedback
      - sonic-frameworks-widgets-addons
      - sonic-frameworks-windowsystem
      - sonic-frameworks-xml-gui
      - sonic-frameworks-zeroconf
      - sonic-gtk-theme-bridge
      - sonic-interface-libraries
      - sonic-keybind-daemon
      - sonic-launcher-menu-edit
      - sonic-login-manager
      - sonic-mobile-interface
      - sonic-network-manager
      - sonic-night-light
      - sonic-oxygen
      - sonic-oxygen-icons
      - sonic-oxygen-sounds
      - sonic-partition-manager
      - sonic-pipewire
      - sonic-plasma5-support-library
      - sonic-polkit
      - sonic-polkit-agent
      - sonic-pulseaudio-library
      - sonic-pyside-setup
      - sonic-qt-accounts-library
      - sonic-qt-theme-bridge
      - sonic-quick-image-editor
      - sonic-rdp-server
      - sonic-screen
      - sonic-screen-library
      - sonic-screenies
      - sonic-screenlocker
      - sonic-silver
      - sonic-silver-gtk
      - sonic-silver-icons
      - sonic-silver-sddm
      - sonic-ssh-password-prompt
      - sonic-system-info
      - sonic-system-log
      - sonic-system-monitor
      - sonic-system-monitor-library
      - sonic-system-stats
      - sonic-terminal
      - sonic-terminal-tools
      - sonic-thunderbolt
      - sonic-tv-interface
      - sonic-vault
      - sonic-welcome-center
      - sonic-win
      - sonic-workspace
      - sonic-workspace-addons
      - sonic-workspace-wallpapers
      - sonic-write-daemon
      - sonicde-meta
      - xdg-desktop-portal-sonicde
    steps:
      - name: Setup workspace
        uses: callmetango/setup-workspace@HEAD
        with:
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}

      - name: Release new release
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: |
          create_repo_db=1; delete_source=1
          . setup-build-env.sh
          copy-release.sh "$REPOSITORY" "$STAGING_TAG" \
              "$REPOSITORY" "$CURRENT_TAG" $create_repo_db $delete_source
